##################################################################################################
## Configuration file for GeneLab for estimation of host reads in Illumina metagenomic datasets ##
## Developed by Michael D. Lee (Mike.Lee@nasa.gov)                                              ##
##################################################################################################

############################################################
##################### VARIABLES TO SET #####################
############################################################

############################################################################
##### This first set of variables needs to match what is on our system #####
############################################################################


## single-column file with unique sample identifiers:
sample_info_file:
    "unique-sample-IDs.txt"

## input reads directory (can be relative to workflow directory, or needs to be full path)
input_reads_dir:
    "example-reads/"

## if data are single-end only (only one read-file per sample), set this to "TRUE", anything else is considered paired-end
single_end_data:
    ""

## raw read suffixes (region following the unique part of the sample names)
  # e.g. for "Sample-1_R1_raw.fastq.gz" would be "_R1_raw.fastq.gz"
input_R1_suffix:
    "_R1.fastq.gz"
input_R2_suffix:
    "_R2.fastq.gz"

    # if single-end data, set this one (others above don't matter)
input_read_suffix:
    "_raw.fastq.gz"

## directory holding kraken2 reference databas
    # this should be provided as a full path (starting with `/` as the below example
    # (note that the the `~/` home shortcut is not expanded
    # by snakemake's evaluation of files, so don't use that)
REF_DB_DIR:
    "/path/to/kraken2/refdb/"


######################################################################
##### The rest only need to be altered if we want to change them #####
######################################################################

## Number of threads to pass to kraken2 call (will be multiplied by number of jobs running, set with the -j parameter in the snakemake call)
num_threads:
    10

## log directory
logs_dir:
    "logs/"

## kraken output files
kraken_outputs:
    "kraken-outputs/"


############################################################
###################### GENERAL INFO ########################
############################################################
# Workflow is currently equipped to work with paired-end data only, and reads are expected to be gzipped


## example usage command ##
# snakemake --use-conda --conda-prefix ${CONDA_PREFIX}/envs -j 2 -p

# `--use-conda` – this specifies to use the conda environments included in the workflow
# `--conda-prefix` – this allows us to point to where the needed conda environments should be stored. Including this means if we use the workflow on a different dataset somewhere else in the future, it will re-use the same conda environments rather than make new ones. The value listed here, `${CONDA_PREFIX}/envs`, is the default location for conda environments (the variable `${CONDA_PREFIX}` will be expanded to the appropriate location on whichever system it is run on).
# `-j` – this lets us set how many jobs Snakemake should run concurrently (keep in mind that many of the thread and cpu parameters set in the config.yaml file will be multiplied by this)
# `-p` – specifies to print out each command being run to the screen

# See `snakemake -h` for more options and details.
